name: deploy

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  placholder:
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: echo "placeholder"

  # This is commented out as i don't have a aws account i want to link to this public repository
  # this assumed you haev a OICD policy in aws that will allow github to assume a role capable of
  # deploying the resources
  #
  # pulumi-up:
  #   runs-on: [self-hosted, ubuntu20.04-self]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.x
  #         cache: npm

  #     - uses: unfor19/install-aws-cli-action@v1
  #       with:
  #         version: 2

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-region: eu-central-1
  #         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

  #     - run: cd pulumi && npm ci
  #     - uses: pulumi/actions@v4
  #       with:
  #         work-dir: pulumi
  #         command: up
  #         stack-name: example
  #       env:
  #         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
